apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: habit-tracker

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - mongodb.yaml
  - backend.yaml
  - frontend.yaml
